program lab1;
uses math ,crt;
var x,e:double;
begin
e:=2.72;
x:=-10.00;
while x<=1 do 
begin
write('x= ');
write(x :6:2);
write(' f(x)= ');
if ((x<0.02) and (x>-0.02)) then write('The value is not defined! ')  
else
begin
if (x<-8.09)  then write(((x**3)/x)*(cos(2*x)/((-1)*(abs(x)**(1/3)))) :1:2)  
else
begin
        if ((x>=-8.02) and (x < -1)) then write(sin(x)/cos(x) - e**x/cos(x) :1:2)  
        else write(((-x/tan(x))*(cos(2*x)/x**2)) :1:2);  
end;
end;
x:=x+0.1;  
writeln();
end; 
read(x);
end.
